name: "Release"

permissions:
  contents: write

on:
  push:
    tags: "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.versions.outputs.nodejs }}
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/lemmy-fast-post.user.js
